server:
    host: 127.0.0.1
    port: 3000
database:
    driver: postgres
    username: postgres
    password: postgres
    host: localhost
    port: 5432
    dbname: superheroes
api:
    endpoint: "https://superheroapi.com/api"
    token: 3185322551504722
